baseURL = 'Creativity-AI-Reading-Group.github.io'
languageCode = 'en-us'
title = 'AI & Creativity Study Group'

[menus]
  [[menus.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menus.main]]
    name = 'Publications'
    pageRef = '/publications'
    weight = 20 # Adjust weight to place it where you want (e.g., between Sessions and Members)
  [[menus.main]]
    name = 'Reading Group'
    pageRef = '/sessions'
    weight = 25
  [[menus.main]]
    name = 'Members'
    pageRef = '/members'
    weight = 30
  [[menus.main]]
    name = 'Resources'
    pageRef = '/resources'
    weight = 40